/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

/**
 *
 * @author mariajesuscanoles
 */
public class Interfaz extends javax.swing.JFrame {
    

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        salir = new javax.swing.JButton();
        workspace = new javax.swing.JLabel();
        index = new javax.swing.JLabel();
        localRepository = new javax.swing.JLabel();
        remoteRepository = new javax.swing.JLabel();
        init = new javax.swing.JButton();
        add = new javax.swing.JButton();
        commit = new javax.swing.JButton();
        nuevoArchivo = new javax.swing.JButton();
        pull = new javax.swing.JButton();
        push = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        getContentPane().add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 0, -1, -1));

        workspace.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        workspace.setText("WORKSPACE");
        getContentPane().add(workspace, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, -1, -1));

        index.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        index.setText("INDEX");
        getContentPane().add(index, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, -1, -1));

        localRepository.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        localRepository.setText("LOCAL REPOSITORY");
        getContentPane().add(localRepository, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 80, -1, -1));

        remoteRepository.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        remoteRepository.setText("REMOTE REPOSITORY");
        getContentPane().add(remoteRepository, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 80, -1, -1));

        init.setText("Init");
        init.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                initActionPerformed(evt);
            }
        });
        getContentPane().add(init, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, -1, -1));

        add.setText("Add");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        getContentPane().add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 460, -1, -1));

        commit.setText("Commit");
        commit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                commitActionPerformed(evt);
            }
        });
        getContentPane().add(commit, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 460, -1, -1));

        nuevoArchivo.setText("Nuevo Archivo");
        nuevoArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoArchivoActionPerformed(evt);
            }
        });
        getContentPane().add(nuevoArchivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 460, -1, -1));

        pull.setText("Pull");
        getContentPane().add(pull, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 460, -1, -1));

        push.setText("Push");
        getContentPane().add(push, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 460, -1, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 100, 140, 260));

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 100, 140, 260));

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jScrollPane3.setViewportView(jTextArea3);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 140, 260));

        jTextArea4.setColumns(20);
        jTextArea4.setRows(5);
        jScrollPane4.setViewportView(jTextArea4);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 140, 260));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_salirActionPerformed

    private void initActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_initActionPerformed
        // TODO add your handling code here:
        GitInit init = new GitInit();
        init.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_initActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
        GitAdd add = new GitAdd();
        add.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_addActionPerformed

    private void commitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_commitActionPerformed
        // TODO add your handling code here:
        GitCommit commit = new GitCommit();
        commit.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_commitActionPerformed

    private void nuevoArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoArchivoActionPerformed
        // TODO add your handling code here:
        CrearArchivo archivo = new CrearArchivo();
        archivo.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_nuevoArchivoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JButton commit;
    private javax.swing.JLabel index;
    private javax.swing.JButton init;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JLabel localRepository;
    private javax.swing.JButton nuevoArchivo;
    private javax.swing.JButton pull;
    private javax.swing.JButton push;
    private javax.swing.JLabel remoteRepository;
    private javax.swing.JButton salir;
    private javax.swing.JLabel workspace;
    // End of variables declaration//GEN-END:variables
}
